spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:contactapi
    username: root
    password: admin
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: false
    hibernate:
      ddl-auto: create-drop
  logging:
    file: contactapi.log
    pattern:
      console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
      file: "%d %-5level [%thread] %logger : %msg%n"
    level:
      root: ERROR
      org.springframework.web: DEBUG
      com.resttechsolutions.contactapi: DEBUG
      org.hibernate: DEBUG
server:
  servlet:
    context-path: /api/v1
